/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package uas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author Asus
 */
public class Parkir extends javax.swing.JFrame {
    
    /**
     * Creates new form Parkir
     */
    public Parkir() {
        initComponents();
        viewTable();
    }
    
    public void clear(){
        PlatNomor2.setText("");
        harga.setText("");
        waktu.setText("");
        pembayaran.setText("");
        kembalian.setText("");
    }

    public int hitungHarga(String type, int waktu){
        int hasil = 0; 
        if(type.equals("Motor")){
            hasil += 5000 * waktu;
            return hasil > 25000? 25000 : hasil;
         }else{
            hasil += 10000 * waktu;
            return hasil > 25000? 25000 : hasil;
         }
    }
    
    public void buatStruk(String waktu, String platNomor, String type){
         TextStruk.setText("");
         String[] c = waktu.split(" ");
         String harga = type.equals("Mobil")? "RP 10.000": "RP 5.000";
         TextStruk.append("\n          PARKIRAN ROXYZC - "+ type +"\n\n");
         TextStruk.append("   Harga     : "+ harga+ "/Jam\n");
         TextStruk.append("   No          : "+ platNomor +"\n");
         TextStruk.append("   Tanggal : "+ c[0] +"\n");
         TextStruk.append("   Waktu    : "+ c[1] +"\n\n");
         TextStruk.append("       Jangan Meninggalkan Tiket dan\n");
         TextStruk.append("            Barang Bawaan Anda");
    }
    
    public void coba(String platNomor){
        try {
            // TODO add your handling code here:
            if(platNomor.equals("Motor") || platNomor.equals("Mobil")){
                TextStruk.setText("");
                return;
            }
            LocalDateTime myDateObj = LocalDateTime.now();
            DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            String formattedDate = myDateObj.format(myFormatObj);
            Connection connection = Koneksi.ConnectDB();
            String query = "SELECT * FROM tb_parkir where platnomor='"+platNomor+"'";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);
            String waktu1 = null;
            String type = null;
            while(rs.next()){
                waktu1 = rs.getString("waktu");
                type = rs.getString("typeKendaraan");
            }
            String[] s = waktu1.split("[-: ]");
            String[] f = formattedDate.split("[-: ]");
            int jam = Integer.parseInt(f[3]) - Integer.parseInt(s[3]);
            int menit = Integer.parseInt(f[4]) - Integer.parseInt(s[4]);
            int detik = Integer.parseInt(f[5]) - Integer.parseInt(s[5]);
            int tanggal = Integer.parseInt(f[0]) - Integer.parseInt(s[0]);           
            st.close();
            buatStruk(waktu1, platNomor, type);
            if(waktu1 == null){
                JOptionPane.showMessageDialog(null, "Invalid", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                
                if(tanggal != 0){
                    jam += tanggal * 24;
                }else if(jam == 0){
                    jam++;
                }else{
                      jam = jam * 60 + menit;
                      System.out.println(jam);
                      jam = (jam / 60 == 0)? 1 : jam/60;
                }
            }
            int h = hitungHarga(type, jam);
            PlatNomor2.setText(platNomor);
            waktu.setText(String.valueOf(jam));
            harga.setText(String.valueOf(h));
          
        } catch (SQLException ex) {
            Logger.getLogger(Parkir.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        pembayaran = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        PlatNomor2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        waktu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Reset = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TextStruk = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        PlatNomor1 = new javax.swing.JTextField();
        ComboBoxType = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel2.setBackground(new java.awt.Color(153, 153, 153));

        jTable1.setBackground(new java.awt.Color(204, 204, 204));
        jTable1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PlatNomor", "Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("PlatNomor");

        pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pembayaranActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Harga");

        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Pembayaran");

        PlatNomor2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlatNomor2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Kembalian");

        waktu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waktuActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Waktu");

        Reset.setBackground(new java.awt.Color(102, 0, 0));
        Reset.setForeground(new java.awt.Color(255, 255, 255));
        Reset.setText("Reset");
        Reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResetMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ResetMousePressed(evt);
            }
        });

        TextStruk.setBackground(new java.awt.Color(204, 204, 204));
        TextStruk.setColumns(20);
        TextStruk.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        TextStruk.setRows(5);
        TextStruk.setToolTipText("");
        TextStruk.setAutoscrolls(false);
        TextStruk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        TextStruk.setMargin(new java.awt.Insets(40, 30, 30, 40));
        TextStruk.setName(""); // NOI18N
        TextStruk.setOpaque(false);
        jScrollPane2.setViewportView(TextStruk);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)
                        .addComponent(PlatNomor2)
                        .addComponent(harga)
                        .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(pembayaran)
                        .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(12, 12, 12)
                        .addComponent(PlatNomor2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(harga, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 26, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(kembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Reset, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PlatNomor");

        ComboBoxType.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ComboBoxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Motor", "Mobil" }));

        btnSimpan.setBackground(new java.awt.Color(204, 204, 204));
        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSimpanMousePressed(evt);
            }
        });
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        BtnDelete.setBackground(new java.awt.Color(255, 204, 204));
        BtnDelete.setText("Delete");
        BtnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnDeleteMouseClicked(evt);
            }
        });

        btnCari.setText("Cari");
        btnCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCariMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PlatNomor1)
                    .addComponent(ComboBoxType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlatNomor1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ComboBoxType, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 887, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private DefaultTableModel tableModel;
    private ResultSet resultSet;
    public void viewTable(){
         try {
             // TODO add your handling code here:
            Object[] columnTitle = {"PlatNomor","Type"};
            tableModel = new DefaultTableModel(null,columnTitle);
            jTable1.setModel(tableModel);
            
            Connection koneksi = Koneksi.ConnectDB();
            Statement statement = koneksi.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            resultSet = statement.executeQuery("SELECT * FROM tb_parkir");
            while(resultSet.next()){
                Object[] data = {
                    resultSet.getString("platnomor"),
                    resultSet.getString("typeKendaraan")
                };
                tableModel.addRow(data);
            }
         } catch (SQLException ex) {
            System.out.println(ex);
         }

    }
    
    private void btnSimpanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanMousePressed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    private void pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pembayaranActionPerformed
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            if(harga.getText().isEmpty() || harga.getText().isBlank()){
                JOptionPane.showMessageDialog(null, "Invalid", "Error", JOptionPane.ERROR_MESSAGE);
            }else if(Integer.parseInt(pembayaran.getText()) < Integer.parseInt(harga.getText())){
                JOptionPane.showMessageDialog(null, "Invalid", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                Connection koneksi = Koneksi.ConnectDB();
                String delete = "DELETE FROM `tb_parkir` WHERE platnomor='"+ PlatNomor2.getText()+"'";
                PreparedStatement prs = koneksi.prepareStatement(delete);
                prs.execute();
                kembalian.setText(String.valueOf(Integer.parseInt(pembayaran.getText()) - Integer.parseInt(harga.getText())));
                viewTable();
                koneksi.close();
            }
           
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Invalid", "ERROR", JOptionPane.ERROR_MESSAGE);
            PlatNomor1.setText("");
            ComboBoxType.setSelectedItem("Select Type");
        }
    }//GEN-LAST:event_pembayaranActionPerformed

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        try {
            // TODO add your handling code here:
            Connection koneksi = Koneksi.ConnectDB();
            if(ComboBoxType.getSelectedItem().equals("Select Type") || (PlatNomor1.getText().isEmpty() || PlatNomor1.getText().isBlank() || PlatNomor1.getText().length() < 5)){
                PlatNomor1.setText("");
                JOptionPane.showMessageDialog(null, "invalid", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                LocalDateTime myDateObj = LocalDateTime.now();
                DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
                String formattedDate = myDateObj.format(myFormatObj);
                String sql = "INSERT INTO `tb_parkir`(`platnomor`, `typeKendaraan`, `waktu`) VALUES ("
                            + "'"+PlatNomor1.getText()+"'"
                            + ",'"+ComboBoxType.getSelectedItem().toString()+"','"+formattedDate+"')";
                PreparedStatement preparedStmt = koneksi.prepareStatement(sql);
                preparedStmt.execute();
                JOptionPane.showMessageDialog(null, "Berhasil ditambahkan", "Success", JOptionPane.INFORMATION_MESSAGE);
                viewTable();
                PlatNomor1.setText("");
                ComboBoxType.setSelectedItem("Select Type");
                koneksi.close();
            }
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Invalid", "ERROR", JOptionPane.ERROR_MESSAGE);
            PlatNomor2.setText("");
            ComboBoxType.setSelectedItem("Select Type");
        }
        
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void waktuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waktuActionPerformed
        try {
            // TODO add your handling code here:
            Connection connection = Koneksi.ConnectDB();
            String query = "SELECT * FROM tb_parkir where platnomor='"+PlatNomor2.getText()+"'";
            Statement st = connection.createStatement();
            ResultSet rs = st.executeQuery(query);
            String type = null;
            while(rs.next()){
                type = rs.getString("typeKendaraan");
            }
            st.close();
            int sum = 0;
            if(type == null || waktu.getText().isBlank() || waktu.getText().isEmpty()){
                JOptionPane.showMessageDialog(null, "Invalid", "ERROR", JOptionPane.ERROR_MESSAGE);
            }else{
                
                if(type.equals("Motor")){
                    sum = 5000 * Integer.parseInt(waktu.getText());
                }
                if(type.equals("Mobil")){
                    sum = 10000 * Integer.parseInt(waktu.getText());
                }
                
                if(sum > 25000){
                    sum = 25000;
                }
                
                harga.setText(String.valueOf(sum));
               
            }
        } catch (SQLException ex) {
            Logger.getLogger(Parkir.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_waktuActionPerformed

    private void PlatNomor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlatNomor2ActionPerformed
        // TODO add your handling code here:
         String plat = PlatNomor2.getText();
         coba(plat);
    }//GEN-LAST:event_PlatNomor2ActionPerformed

    private void ResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMouseClicked
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_ResetMouseClicked

    private void ResetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResetMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_ResetMousePressed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
          String selectedCellValue = (String) jTable1.getValueAt(jTable1.getSelectedRow() , jTable1.getSelectedColumn());
          coba(selectedCellValue);
    }//GEN-LAST:event_jTable1MouseClicked

    private void BtnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnDeleteMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Connection koneksi = Koneksi.ConnectDB();
            String query = "SELECT * FROM tb_parkir where platnomor='"+PlatNomor1.getText()+"'";
            Statement st = koneksi.createStatement();
            ResultSet rs = st.executeQuery(query);
            String platNomor = null;
            while(rs.next()){
                platNomor = rs.getString("platnomor");
            }
            st.close();
            if(PlatNomor1.getText().isEmpty() || PlatNomor1.getText().isBlank()|| platNomor == null){
                JOptionPane.showMessageDialog(null, "Invalid", "Error", JOptionPane.ERROR_MESSAGE);
            }else{
                String delete = "DELETE FROM `tb_parkir` WHERE platnomor='"+platNomor+"'";
                PreparedStatement prs = koneksi.prepareStatement(delete);
                prs.execute();
                PlatNomor1.setText("");
                viewTable();
                TextStruk.setText("");
                koneksi.close();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Invalid", "ERROR", JOptionPane.ERROR_MESSAGE);
            PlatNomor1.setText("");
            ComboBoxType.setSelectedItem("Select Type");
        }
    }//GEN-LAST:event_BtnDeleteMouseClicked

    private void btnCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCariMouseClicked
        // TODO add your handling code here:
         try {
            Object[] columnTitle = {"PlatNomor","Type"};
            tableModel = new DefaultTableModel(null,columnTitle);
            jTable1.setModel(tableModel);
            
            Connection koneksi = Koneksi.ConnectDB();
            Statement statement = koneksi.createStatement();
            tableModel.getDataVector().removeAllElements();
            
            if((PlatNomor1.getText().isBlank() || PlatNomor1.getText().isEmpty()) && "Select Type".equals(ComboBoxType.getSelectedItem().toString())){
                resultSet = statement.executeQuery("SELECT * FROM tb_parkir");
                while(resultSet.next()){
                    Object[] data = {
                        resultSet.getString("platnomor"),
                        resultSet.getString("typeKendaraan")
                    };
                    tableModel.addRow(data);
                }
                PlatNomor1.setText("");
            }else if((PlatNomor1.getText().isEmpty() || PlatNomor1.getText().isBlank()) && !"Select Type".equals(ComboBoxType.getSelectedItem().toString())){
                resultSet = statement.executeQuery("SELECT * FROM tb_parkir WHERE typeKendaraan='"+ComboBoxType.getSelectedItem().toString()+"'");
                    while(resultSet.next()){
                        Object[] data = {
                            resultSet.getString("platnomor"),
                            resultSet.getString("typeKendaraan")
                        };
                        tableModel.addRow(data);
                    }
                    ComboBoxType.setSelectedItem("Select Type");
            }else if(PlatNomor1.getText() != null && "Select Type".equals(ComboBoxType.getSelectedItem().toString())){ 
                  resultSet = statement.executeQuery("SELECT * FROM tb_parkir WHERE platnomor='"+PlatNomor1.getText()+"'");
                    while(resultSet.next()){
                        Object[] data = {
                            resultSet.getString("platnomor"),
                            resultSet.getString("typeKendaraan")
                        };
                        tableModel.addRow(data);
                    }
                    PlatNomor1.setText("");
            }else{
                resultSet = statement.executeQuery("SELECT * FROM tb_parkir WHERE platnomor='"+PlatNomor1.getText()+"' AND typeKendaraan='"+ComboBoxType.getSelectedItem().toString()+"'");
                    while(resultSet.next()){
                        Object[] data = {
                            resultSet.getString("platnomor"),
                            resultSet.getString("typeKendaraan")
                        };
                        tableModel.addRow(data);
                    }
                    PlatNomor1.setText("");
                    ComboBoxType.setSelectedItem("Select Type");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Invalid", "ERROR", JOptionPane.ERROR_MESSAGE);
            PlatNomor1.setText("");
            ComboBoxType.setSelectedItem("Select Type");
        }
    }//GEN-LAST:event_btnCariMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parkir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parkir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnDelete;
    private javax.swing.JComboBox<String> ComboBoxType;
    private javax.swing.JTextField PlatNomor1;
    private javax.swing.JTextField PlatNomor2;
    private javax.swing.JButton Reset;
    private javax.swing.JTextArea TextStruk;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField pembayaran;
    private javax.swing.JTextField waktu;
    // End of variables declaration//GEN-END:variables
}
